include=~~/profiles.conf

vo=gpu-next
hwdec=auto

cache=auto
demuxer-max-bytes=512MiB
demuxer-readahead-secs=20

scale=spline36
cscale=spline36
dscale=mitchell
deband=yes

keep-open=no
save-position-on-quit=no
cursor-autohide=100

autofit=80%
border=no

background-color='#1e1e2e'
osd-back-color='#11111b'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'

script-opts-append=stats-border_color=251818
script-opts-append=stats-font_color=f4d6cd
script-opts-append=stats-plot_bg_border_color=aca0eb
script-opts-append=stats-plot_bg_color=251818
script-opts-append=stats-plot_color=aca0eb
script-opts-append=uosc-color=foreground=eba0ac,foreground_text=313244,background=1e1e2e,background_text=cdd6f4,curtain=181825,success=a6e3a1,error=f38ba8
