[low]
profile=fast
ytdl-format=bestvideo*[height<=?480]+bestaudio/best[height<=?480]

[medium]
profile=fast
ytdl-format=bestvideo*[height<=?720]+bestaudio/best[height<=?720]

[high]
profile=high-quality
