[projects.'d:\ca\cases\2026\nexusdb']
trust_level = "trusted"

[projects.'d:\notes\workflow\envcross_dotfiles']
trust_level = "trusted"

[windows]
sandbox = "elevated"

[mcp_servers.tavily]
type = "http"
url = "https://mcp.tavily.com/mcp/"

[hooks.state]

[hooks.state.'C:\Users\Lou\.codex\hooks.json:post_tool_use:0:0']
trusted_hash = "sha256:123ae5c4a74139970e747025f52f1bff10b4b0c03cadfbb1d0100bb65d4e30d5"

[hooks.state.'C:\Users\Lou\.codex\hooks.json:session_start:0:0']
trusted_hash = "sha256:884a835c2bfa6a80fc9724a3137e4dd90603e6435a7e8e3e6ca12a63a49f12da"
